{
 "title": "Warnsystem AKCP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SystemName",
    "label": "System Name",
    "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemName\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
   },
   {
    "name": "AgentHost",
    "label": "Agent Host",
    "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemName\")\r\n  |> filter(fn: (r) => r[\"_value\"] == \"${SystemName}\")\r\n  |> keep(columns: [\"agent_host\"])"
   },
   {
    "name": "LiquidActivePort",
    "label": "Liquid Active Port",
    "query": "import \"strings\"\r\n\r\nfrom(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^LiquidDescriptionPort\\d+$/)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> distinct(column: \"_field\")\r\n  |> map(fn: (r) => ({r with _field: strings.replace(v: r._field, t: \"LiquidDescriptionPort\", u: \"\", i: 1)}))\r\n  |> group()"
   },
   {
    "name": "TempActivePort",
    "label": "Temp Active Port",
    "query": "import \"strings\"\r\n\r\nfrom(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^TempDescriptionPort\\d+$/)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> distinct(column: \"_field\")\r\n  |> map(fn: (r) => ({r with _field: strings.replace(v: r._field, t: \"TempDescriptionPort\", u: \"\", i: 1)}))\r\n  |> group()\r\n"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Name",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemName\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
    }
   ]
  },
  {
   "title": "System Location",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemLocation\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
    }
   ]
  },
  {
   "title": "System Contact",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemContact\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "targets": [
    {
     "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpTime\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
    }
   ]
  },
  { "title": "Temperature status port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": ".",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "repeat": "TempActivePort",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^TempDescriptionPort${TempActivePort:regex}$/)\r\n  |> group()\r\n  |> distinct(column: \"_value\")"
    }
   ]
  },
  {
   "title": ".",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "repeat": "TempActivePort",
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TempDegreePort${TempActivePort}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Temperature degree ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": ".",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
     "repeat": "TempActivePort",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^TempDescriptionPort${TempActivePort:regex}$/)\r\n  |> group()\r\n  |> distinct(column: \"_value\")"
      }
     ]
    },
    {
     "title": ".",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "repeat": "TempActivePort",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TempStatusPort${TempActivePort}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Liquid status port",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": ".",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
     "repeat": "LiquidActivePort",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^LiquidDescriptionPort${LiquidActivePort:regex}$/)\r\n  |> group()\r\n  |> distinct(column: \"_value\")"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
     "repeat": "LiquidActivePort",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"warn\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${AgentHost}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"LiquidStatusPort${LiquidActivePort}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
      }
     ]
    }
   ]
  }
 ]
}