{
 "title": "Windows Server Summary",
 "description": "Windows Server Status using Prometheus and windows_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Domain",
    "label": "Domain",
    "query": {
     "query": "label_values(windows_cs_hostname,domain)"
    }
   },
   {
    "name": "WindowsVersion",
    "query": {
     "query": "label_values(windows_os_info,product)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Domains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Server $Domain",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "repeat": "Domain",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(windows_cs_hostname{domain=~\"$Domain\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Windows Versions ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "Total $WindowsVersion",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "repeat": "WindowsVersion",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(windows_os_info{product=~\"$WindowsVersion\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Servers",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "aggregation": "Last",
     "bucketAggs": [
      {
       "$$hashKey": "object:862",
       "fake": true,
       "field": "host.hostname",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "avg by (instance) (windows_cs_logical_processors)",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "{{instance}}",
     "metrics": [
      {
       "$$hashKey": "object:850",
       "field": "system.cpu.cores",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:851",
       "field": "system.cpu.total.norm.pct",
       "id": "4",
       "meta": {},
       "pipelineVariables": [
        { "name": "user", "pipelineAgg": "10" },
        { "name": "system", "pipelineAgg": "9" }
       ],
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:852",
       "field": "system.memory.actual.used.pct",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:853",
       "field": "system.fsstat.total_size.used",
       "hide": true,
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:854",
       "field": "system.fsstat.total_size.total",
       "hide": true,
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:855",
       "field": "select field",
       "id": "8",
       "meta": {},
       "pipelineVariables": [
        { "name": "disk_used", "pipelineAgg": "6" },
        { "name": "disk_cap", "pipelineAgg": "7" }
       ],
       "settings": {
        "script": "params.disk_used/params.disk_cap"
       },
       "type": "bucket_script"
      }
     ],
     "timeField": "@timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(((windows_cs_physical_memory_bytes - windows_os_physical_memory_free_bytes) / windows_cs_physical_memory_bytes) * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - ((windows_logical_disk_free_bytes{volume=\"C:\"} / windows_logical_disk_size_bytes{volume=\"C:\"})*100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - ((windows_logical_disk_free_bytes{volume=\"D:\"} / windows_logical_disk_size_bytes{volume=\"D:\"})*100)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}