{
 "title": "Cisco SG 300 Switch",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SwitchName",
    "label": "Switch Name",
    "query": "from(bucket: \"cisco\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Switch\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemName\")\r\n  |> yield(name: \"last\")"
   },
   {
    "name": "IP",
    "label": "IP",
    "query": "from(bucket: \"cisco\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_value\"] == \"${SwitchName}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemName\")\r\n  |> distinct(column: \"agent_host\")"
   },
   {
    "name": "PortDescription",
    "label": "Port Description",
    "query": "import \"strings\"\r\n\r\nfrom(bucket: \"cisco\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^PortDescription\\d+$/)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${IP}\")\r\n  |> distinct(column: \"_field\")\r\n  |> map(fn: (r) => ({r with _field: strings.replace(v: r._field, t: \"PortDescription\", u: \"\", i: 1)}))\r\n  |> group()\r\n"
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${IP}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemName\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
    }
   ]
  },
  {
   "title": "System Location",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${IP}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemLocation\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
    }
   ]
  },
  {
   "title": "System Description",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${IP}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemDescription\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
    }
   ]
  },
  {
   "title": "System Up Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${IP}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemUpTime\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
    }
   ]
  },
  { "title": "Port Descorption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Port Description $PortDescription",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "repeat": "PortDescription",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"cisco\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${IP}\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"PortDescription${PortDescription}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
    }
   ]
  }
 ]
}