{
 "title": "USVs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host_ABB",
    "label": "Host_ABB",
    "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"abb\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"agent_host\"])\r\n  |> distinct(column: \"agent_host\")\r\n  |> group()"
   },
   {
    "name": "Host_Schneider",
    "label": "Host_Schneider",
    "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"schneider\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"agent_host\"])\r\n  |> distinct(column: \"agent_host\")\r\n  |> group()\r\n"
   },
   {
    "name": "Host_Netman",
    "label": "Host_Netman",
    "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netman\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"agent_host\"])\r\n  |> distinct(column: \"agent_host\")\r\n  |> group()\r\n"
   }
  ]
 },
 "panels": [
  { "title": "Schneider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "InputFrequency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"schneider\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"InputFrequency\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "InputVoltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"schneider\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"InputVoltage\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "OutputFrequency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"schneider\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputFrequency\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "OutputLoad",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"schneider\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputLoad\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"schneider\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputVoltage\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "BatteryVoltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryVoltage\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BatteryCapacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryCapacity\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BatteryTemperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryTemperature\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BatteryRunTimeRemaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryRunTimeRemaining\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BatteryRunTimeRemaining",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputLoad\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Netman",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "upsInputCurrent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputCurrent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputLineIndex",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputLineIndex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputTruePower",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputTruePower\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputFrequency",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputFrequency\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputVoltage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputVoltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsAlarmsPresent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsAlarmsPresent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputCurrent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputCurrent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputLineIndex",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputLineIndex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputPercemtLoad",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputPercentLoad\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputPower",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 13, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"172.31.10.10\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputPower\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputVoltage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"172.31.10.10\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputVoltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsBatteryCurrent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"172.31.10.10\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsBatteryCurrent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsBatteryStatus",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"172.31.10.10\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsBatteryStatus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsBatteryVoltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 6, "y": 22 },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsBatteryVoltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsBatteryTemperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 10, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"172.31.10.10\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsBatteryTemperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsEstimatedMinutesRemaining",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 13, "y": 22 },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEstimatedMinutesRemaining\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsEstimatedChargeRemaining",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEstimatedChargeRemaining\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsSecondsOnBattery",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsSecondsOnBattery\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Abb Input ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "upsInputCurrent1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputCurrent1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputLineIndex1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputLineIndex1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputFrequency1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputFrequency1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputTruePower1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputTruePower1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputVoltage1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputVoltage1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputCurrent2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputCurrent2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputLineIndex2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputLineIndex2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputFrequency1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputFrequency2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputTruePower2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputTruePower2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputVoltage2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputVoltage2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputCurrent3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputCurrent3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputLineIndex3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputLineIndex3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputFrequency3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputFrequency3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputTruePower3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputTruePower3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputVoltage3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsInputVoltage3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Abb Output ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "upsOutputCurrent1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputCurrent1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputLineIndex1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputLineIndex1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputPower1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputPower1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputPercentLoad1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputPercentLoad1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputVoltage1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputVoltage1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputCurrent2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputCurrent2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputLineIndex2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputLineIndex2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputPower2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputPower2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputPercentLoad2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputPercentLoad2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputVoltage2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputVoltage2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputCurrent3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputCurrent3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputCurrent3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputCurrent3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputPower3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputPower3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputPercentLoad3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputPercentLoad3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsOutputVoltage3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsOutputVoltage3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Abb Battery ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "upsEstimatedMinutesRemaining",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEstimatedMinutesRemaining\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsBatteryCurrent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsBatteryCurrent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsBatteryTemperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsBatteryTemperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsBatteryStatus",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsBatteryStatus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsEstimatedChargeRemaining",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsEstimatedChargeRemaining\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsSecondsOnBattery",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsSecondsOnBattery\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsBatteryVoltage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsBatteryVoltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Abb Alarm ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "upsAlarmsPresent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upsAlarmsPresent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}