{
 "title": "USVs",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host_ABB",
    "label": "Host_ABB",
    "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Abb\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"agent_host\"])\r\n  |> distinct(column: \"agent_host\")\r\n  |> group()"
   },
   {
    "name": "Host_Schneider",
    "label": "Host_Schneider",
    "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Schneider\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"agent_host\"])\r\n  |> distinct(column: \"agent_host\")\r\n  |> group()"
   },
   {
    "name": "Host_Netman",
    "label": "Host_Netman",
    "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netman\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"agent_host\"])\r\n  |> distinct(column: \"agent_host\")\r\n  |> group()\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Schneider",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "InputFrequency",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Schneider\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"InputFrequency\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "InputVoltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Schneider\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"InputVoltage\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")\r\n"
      }
     ]
    },
    {
     "title": "OutputFrequency",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Schneider\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputFrequency\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")\r\n"
      }
     ]
    },
    {
     "title": "OutputLoad",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Schneider\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputLoad\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")\r\n"
      }
     ]
    },
    {
     "title": "OutputVoltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Schneider\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputVoltage\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")\r\n"
      }
     ]
    },
    {
     "title": "BatteryVoltage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryVoltage\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "BatteryCapacity",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryCapacity\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "BatteryTemperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryTemperature\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "BatteryRunTimeRemaining",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryRunTimeRemaining\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "BatteryRunTimeRemaining",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputLoad\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Schneider}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean\")\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Netman",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "UpsInputCurrent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputCurrent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputLineIndex",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputLineIndex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputTruePower",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputTruePower\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "upsInputFrequency",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputFrequency\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputVoltage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputVoltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsAlarmsPresent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsAlarmsPresent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsOutputCurrent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputCurrent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsOutputLineIndex",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputLineIndex\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsOutputPercemtLoad",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputPercentLoad\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsOutputPower",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 13, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputPower\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsOutputVoltage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputVoltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsBatteryCurrent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsBatteryCurrent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsBatteryStatus",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsBatteryStatus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsBatteryVoltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 6, "y": 50 },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsBatteryVoltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsBatteryTemperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 10, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsBatteryTemperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsEstimatedMinutesRemaining",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 13, "y": 50 },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsEstimatedMinutesRemaining\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsEstimatedChargeRemaining",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsEstimatedChargeRemaining\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsSecondsOnBattery",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_Netman}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsSecondsOnBattery\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Abb Input ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "UpsInputCurrent1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputCurrent1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputLineIndex1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputLineIndex1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputFrequency1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputFrequency1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputTruePower1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputTruePower1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputVoltage1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputVoltage1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputCurrent2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputCurrent2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputLineIndex2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputLineIndex2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputFrequency1",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputFrequency2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputTruePower2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputTruePower2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputVoltage2",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputVoltage2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputCurrent3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputCurrent3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputLineIndex3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputLineIndex3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputFrequency3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputFrequency3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputTruePower3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputTruePower3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsInputVoltage3",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsInputVoltage3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  { "title": "Abb Output ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "UpsOutputCurrent1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputCurrent1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputLineIndex1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputLineIndex1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputPower1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputPower1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputPercentLoad1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputPercentLoad1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputVoltage1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputVoltage1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputCurrent2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputCurrent2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputLineIndex2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputLineIndex2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputPower2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputPower2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputPercentLoad2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputPercentLoad2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputVoltage2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputVoltage2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputCurrent3",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputCurrent3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputCurrent3",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputCurrent3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputPower3",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputPower3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputPercentLoad3",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputPercentLoad3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UpsOutputVoltage3",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsOutputVoltage3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Abb Battery ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "UpsEstimatedMinutesRemaining",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsEstimatedMinutesRemaining\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsBatteryCurrent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsBatteryCurrent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsBatteryTemperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsBatteryTemperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsBatteryStatus",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsBatteryStatus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsEstimatedChargeRemaining",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsEstimatedChargeRemaining\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsSecondsOnBattery",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsSecondsOnBattery\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "UpsBatteryVoltage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsBatteryVoltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Abb Alarm ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "UpsAlarmsPresent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"usv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"${Host_ABB}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpsAlarmsPresent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}