{
 "title": "Cisco Nexus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "label": "Hostname",
    "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"Name\")\n  |> keep(columns: [\"_value\"])  "
   },
   {
    "name": "Interface",
    "label": "Interface",
    "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifAdminStatus\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"ifName\"])\n"
   },
   {
    "name": "SensorTypes",
    "label": "Sensor Types Nr",
    "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorType\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n  |> last(column: \"_time\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Up Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Inventar",
     "type": "table",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Name\" or r[\"_field\"] == \"Place\" or r[\"_field\"] == \"Os\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"agent_host\"], mode:\"by\")\n  |> last(column: \"_time\")"
      }
     ]
    },
    {
     "title": "Power Supply Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PSU_Status\")\n  |> last(column: \"_value\")\n  |> group()\n  |> count()"
      }
     ]
    },
    {
     "title": "Power Supply Satus",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 9 },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PSU_Status\")\n  |> last()\n  |> map(fn: (r) => ({ r with Index: r.index }))\n  |> keep(columns: [\"_value\", \"Index\", \"source\"])"
      }
     ]
    },
    {
     "title": "Fan Satus",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 9 },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FAN_Status\")\n  |> last()\n  |> map(fn: (r) => ({ r with Index: r.index }))\n  |> keep(columns: [\"_value\", \"Index\", \"source\"])"
      }
     ]
    },
    {
     "title": "Fan Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FAN_Status\")\n  |> last(column: \"_value\")\n  |> group()\n  |> count()"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "typ = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorType\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n\nvalue = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorValue\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n\nname = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorName\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"172.19.0.47\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n\nprecision = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorPrecision\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n\nscale = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorScale\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"172.19.0.47\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n\nstatus = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorStatus\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n\njoin1 = join(\n  tables: {typ: typ, value: value},\n  on: [\"_time\", \"index\"]\n)\n\njoin2 = join(\n  tables: {join1: join1, name: name},\n  on: [\"_time\", \"index\"]\n)\n\njoin3 = join(\n  tables: {join2: join2, precision: precision},\n  on: [\"_time\", \"index\"]\n)\n\njoin4 = join(\n  tables: {join3: join3, scale: scale},\n  on: [\"_time\", \"index\"]\n)\n\nfinalJoin = join(\n  tables: {join4: join4, status: status},\n  on: [\"_time\", \"index\"]\n)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      index: r.index,\n      SensorName: r[\"_value_join2\"],\n      SensorStatus: r[\"_value_status\"],\n      SensorPrecision: r[\"_value_precision\"],\n      SensorScale: r[\"_value_join4\"],\n      SensorType: r[\"_value_typ\"],\n      OriginalValue: r[\"_value_value\"],\n      TransformedValue: if r[\"_value_join4\"] == 8 then float(v: r[\"_value_value\"]) / 1000.0\n                        else if r[\"_value_join4\"] == 9 then float(v: r[\"_value_value\"])\n                        else if r[\"_value_join4\"] == 7 then float(v: r[\"_value_value\"]) / 1000000.0\n                        else if r[\"_value_join4\"] == 6 then float(v: r[\"_value_value\"]) / 1000000000.0\n                        else if r[\"_value_join4\"] == 5 then float(v: r[\"_value_value\"]) / 1000000000000.0\n                        else if r[\"_value_join4\"] == 4 then float(v: r[\"_value_value\"]) / 1000000000000000.0\n                        else if r[\"_value_join4\"] == 3 then float(v: r[\"_value_value\"]) / 1000000000000000000.0\n                        else if r[\"_value_join4\"] == 2 then float(v: r[\"_value_value\"]) / 1000000000000000000000.0\n                        else if r[\"_value_join4\"] == 1 then float(v: r[\"_value_value\"]) / 1000000000000000000000000.0\n                        else if r[\"_value_join4\"] == 10 then float(v: r[\"_value_value\"]) * 1000.0\n                        else if r[\"_value_join4\"] == 11 then float(v: r[\"_value_value\"]) * 1000000.0\n                        else if r[\"_value_join4\"] == 12 then float(v: r[\"_value_value\"]) * 1000000000.0\n                        else if r[\"_value_join4\"] == 13 then float(v: r[\"_value_value\"]) * 1000000000000.0\n                        else if r[\"_value_join4\"] == 14 then float(v: r[\"_value_value\"]) * 1000000000000000.0\n                        else if r[\"_value_join4\"] == 15 then float(v: r[\"_value_value\"]) * 1000000000000000000.0\n                        else if r[\"_value_join4\"] == 16 then float(v: r[\"_value_value\"]) * 1000000000000000000000.0\n                        else if r[\"_value_join4\"] == 17 then float(v: r[\"_value_value\"]) * 1000000000000000000000000.0\n                        else float(v: r[\"_value_value\"])\n  }))\n  |> filter(fn: (r) => r[\"SensorType\"] == 8)\n  |> map(fn: (r) => ({ r with _value: r.TransformedValue }))\n  |> keep(columns: [\"_time\", \"SensorName\", \"_value\"])  \n  |> group(columns: [\"SensorName\"], mode:\"by\")\n  |> yield(name: \"final_results\")"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CPU1m\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> last(column: \"_value\")\n"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CPU1m\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MemUsed\" or r[\"_field\"] == \"MemFree\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (float(v: r.MemUsed) * 100.0) / (float(v: r.MemFree) + float(v: r.MemUsed)) }))\n  |> last(column: \"_value\")\n  |> keep(columns: [\"_value\"])\n"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MemUsed\")"
      }
     ]
    }
   ]
  },
  {
   "title": "All Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "repeat": "SensorTypes",
     "targets": [
      {
       "query": "typ = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorType\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n  |> last(column: \"_time\")\n\nvalue = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorValue\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n  |> last(column: \"_time\")\n\nname = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorName\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"172.19.0.47\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n  |> last(column: \"_time\")\n\nprecision = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorPrecision\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n  |> last(column: \"_time\")\n\nscale = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorScale\")\n  |> filter(fn: (r) => r[\"agent_host\"] == \"172.19.0.47\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n  |> last(column: \"_time\")\n\nstatus = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SensorStatus\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> keep(columns: [\"_time\", \"_value\", \"index\"])  \n  |> last(column: \"_time\")\n\njoin1 = join(\n  tables: {typ: typ, value: value},\n  on: [\"_time\", \"index\"]\n)\n\njoin2 = join(\n  tables: {join1: join1, name: name},\n  on: [\"_time\", \"index\"]\n)\n\njoin3 = join(\n  tables: {join2: join2, precision: precision},\n  on: [\"_time\", \"index\"]\n)\n\njoin4 = join(\n  tables: {join3: join3, scale: scale},\n  on: [\"_time\", \"index\"]\n)\n\nfinalJoin = join(\n  tables: {join4: join4, status: status},\n  on: [\"_time\", \"index\"]\n)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      index: r.index,\n      SensorName: r[\"_value_join2\"],\n      SensorStatus: r[\"_value_status\"],\n      SensorPrecision: r[\"_value_precision\"],\n      SensorScale: r[\"_value_join4\"],\n      SensorType: r[\"_value_typ\"],\n      OriginalValue: r[\"_value_value\"],\n      TransformedValue: if r[\"_value_join4\"] == 8 then float(v: r[\"_value_value\"]) / 1000.0\n                        else if r[\"_value_join4\"] == 9 then float(v: r[\"_value_value\"])\n                        else if r[\"_value_join4\"] == 7 then float(v: r[\"_value_value\"]) / 1000000.0\n                        else if r[\"_value_join4\"] == 6 then float(v: r[\"_value_value\"]) / 1000000000.0\n                        else if r[\"_value_join4\"] == 5 then float(v: r[\"_value_value\"]) / 1000000000000.0\n                        else if r[\"_value_join4\"] == 4 then float(v: r[\"_value_value\"]) / 1000000000000000.0\n                        else if r[\"_value_join4\"] == 3 then float(v: r[\"_value_value\"]) / 1000000000000000000.0\n                        else if r[\"_value_join4\"] == 2 then float(v: r[\"_value_value\"]) / 1000000000000000000000.0\n                        else if r[\"_value_join4\"] == 1 then float(v: r[\"_value_value\"]) / 1000000000000000000000000.0\n                        else if r[\"_value_join4\"] == 10 then float(v: r[\"_value_value\"]) * 1000.0\n                        else if r[\"_value_join4\"] == 11 then float(v: r[\"_value_value\"]) * 1000000.0\n                        else if r[\"_value_join4\"] == 12 then float(v: r[\"_value_value\"]) * 1000000000.0\n                        else if r[\"_value_join4\"] == 13 then float(v: r[\"_value_value\"]) * 1000000000000.0\n                        else if r[\"_value_join4\"] == 14 then float(v: r[\"_value_value\"]) * 1000000000000000.0\n                        else if r[\"_value_join4\"] == 15 then float(v: r[\"_value_value\"]) * 1000000000000000000.0\n                        else if r[\"_value_join4\"] == 16 then float(v: r[\"_value_value\"]) * 1000000000000000000000.0\n                        else if r[\"_value_join4\"] == 17 then float(v: r[\"_value_value\"]) * 1000000000000000000000000.0\n                        else float(v: r[\"_value_value\"])\n  }))\n  |> filter(fn: (r) => r[\"SensorType\"] == ${SensorTypes})\n  |> yield(name: \"final_results\")\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Vlan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "import \"strings\"\n\n// Lade VLAN-Daten mit Namen und behalte die Index-Spalte\nvlans = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r._measurement == \"VLAN\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {index: \"vmVlan\"}) // Umbenennen der Spalte index in vmVlan\n  |> keep(columns: [\"vmVlan\", \"vlanName\", \"vlanDot10Said\", \"vlanMtu\", \"vlanState\", \"vlanType\"])\n  |> map(fn: (r) => ({\n      r with vmVlan: strings.replaceAll(v: string(v: r.vmVlan), t: \"'\", u: \"\")\n    }))\n  |> map(fn: (r) => ({\n      r with vmVlan: strings.replaceAll(v: r.vmVlan, t: \",\", u: \"\")\n    }))\n  |> map(fn: (r) => ({\n      r with vmVlan: if strings.hasPrefix(v: r.vmVlan, prefix: \"1.\") then strings.trimPrefix(v: r.vmVlan, prefix: \"1.\") else r.vmVlan\n    }))\n  |> last(column: \"vlanName\")\n\nvlan_membership = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r._measurement == \"VlanMembership\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> rename(columns: {index: \"ifIndex\"}) // Umbenennen der Spalte index in ifIndex\n  |> map(fn: (r) => ({ r with ifIndex: string(v: r.ifIndex) })) // Konvertiere ifIndex zu String\n  |> last(column: \"vmVlan\")\n\ninterfaces = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifDescr\" or r[\"_field\"] == \"ifIndex\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with ifIndex: string(v: r.ifIndex) })) // Konvertiere ifIndex zu String\n  |> last(column: \"ifName\")  \n\n\nvlan_interfaces = join(\n  tables: {vlan_membership: vlan_membership, interfaces: interfaces},\n  on: [\"ifIndex\"]\n)\n\nresult = join(\n  tables: {vlans: vlans, vlan_interfaces: vlan_interfaces},\n  on: [\"vmVlan\"]\n)\n  |> map(fn: (r) => ({ r with VlanID: r.vmVlan }))\n\nresult\n"
      }
     ]
    }
   ]
  },
  {
   "title": "VPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VPC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"source\", \"index\", \"vpcSystemOperMacAddress\", \"vpcLocalRoleAdminPriority\", \"vpcLocalRoleOperPriority\", \"vpcPeerKeepAliveTime\", \"vpcRoleStatus\", \"vpcPeerKeepAliveStatus\" \"vpcSystemAdminMacAddress\", \"vpcSystemAdminPriority\", \"vpcSystemOperMacAddress\", \"vpcSystemOperPriority\", \"vpcLocalOperMacAddress\"])\n  |> group(columns: [\"source\", \"index\"], mode:\"by\")\n  |> last(column: \"_time\")\n  |> map(fn: (r) => ({ r with Name: r.source }))\n  |> map(fn: (r) => ({ r with Index: r.index }))\n"
      }
     ]
    }
   ]
  },
  { "title": "Interface Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Interface Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "status = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"ifOperStatus\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"ifName\"] =~ /^${Interface:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> rename(columns: {_value: \"_value_status\"})\n  |> last(column: \"_value_status\")\n\n\nadmin = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"ifAdminStatus\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"ifName\"] =~ /^${Interface:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> rename(columns: {_value: \"_value_admin\"})\n  |> last(column: \"_value_admin\")\n\nspeed = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"ifHighSpeed\")\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r[\"ifName\"] =~ /^${Interface:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> rename(columns: {_value: \"_value_speed\"})\n  |> last(column: \"_value_speed\")\n\nstatus_admin = join(\n  tables: {status: status, admin: admin},\n  on: [\"_time\", \"ifName\"]\n)\n\nfinal_join = join(\n  tables: {status_admin: status_admin, speed: speed},\n  on: [\"_time\", \"ifName\"]\n)\n\nfinal_join\n  |> map(fn: (r) => ({ r with Port: r.ifName }))\n  |> map(fn: (r) => ({ r with OperStatusCause: r.ifOperStatusCause_status }))\n  |> keep(columns: [\"_time\", \"_value_status\", \"_value_admin\", \"_value_speed\", \"ifName\", \"Port\", \"agent_host\", \"OperStatusCause\" ])\n  |> last(column: \"_value_admin\")\n"
    }
   ]
  },
  {
   "title": "STP Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "import \"strings\"\n\n// Query for interface data\ninterface = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IF\" and r[\"_field\"] == \"ifDescr\" and r[\"source\"] == \"${Hostname}\")\n  |> keep(columns: [\"index\", \"_value\", \"_time\"])\n  |> last(column: \"index\")\n  |> map(fn: (r) => ({ r with PortIndex: r.index }))\n\n// Query for stb data\nstb = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"STP\" and r[\"source\"] == \"${Hostname}\" and r[\"_field\"] == \"dot1dBasePortIfIndex\")\n  |> keep(columns: [\"_value\", \"index\", \"_time\"])\n  |> last(column: \"index\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      PortIndex: strings.replaceAll(v: string(v: r._value), t: \"'\", u: \"\"),\n      index_stb: r.index\n  }))\n\n// Updated query for STP_PortState, including STP_PortDesignatedRoot and STP_PortPathCost\nstp_port_state = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"STP\" and r[\"source\"] == \"${Hostname}\" and (r[\"_field\"] == \"STP_PortState\" or r[\"_field\"] == \"STP_PortDesignatedRoot\" or r[\"_field\"] == \"STP_PortPathCost\"))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      index_stb: r.index, // Assuming 'index' is part of the pivot\n      PortState: r.STP_PortState,\n      PortDesignatedRoot: r.STP_PortDesignatedRoot,\n      PortPathCost: r.STP_PortPathCost\n  }))\n  |> keep(columns: [\"index_stb\", \"PortState\", \"PortDesignatedRoot\", \"PortPathCost\"])\n\n// First join between stb and interface on PortIndex\njoined_results = join(\n  tables: {stb: stb, iface: interface},\n  on: [\"PortIndex\"]\n)\n\n// Second join including the stp_port_state\nfinal_join = join(\n  tables: {status_admin: joined_results, stp_state: stp_port_state},\n  on: [\"index_stb\"]\n)\n  |> yield(name: \"finalResults\")\n"
    }
   ]
  },
  {
   "title": "LACP Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "import \"strings\"\n\n// Retrieve interface descriptions\ninterfaces = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  // Definieren des Zeitbereichs\n  |> filter(fn: (r) => r._measurement == \"IF\")  // Filtern nach Messung \"IF\"\n  |> filter(fn: (r) => r._field == \"ifDescr\" or r._field == \"ifName\" or r._field == \"ifIndex\")  // Filtern nach relevanten Feldern\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Pivotieren der Daten, um Felder als Spalten zu haben\n  |> map(fn: (r) => ({\n      r with\n      ifIndex_str: string(v: r.ifIndex)  // Umwandeln des ifIndex-Felds in eine Zeichenfolge\n  }))\n  |> map(fn: (r) => ({\n      r with\n      PortIndex: strings.replaceAll(v: r.ifIndex_str, t: \"’\", u: \"\")  // Ersetzen von nicht-numerischen Zeichen und Umbenennen in PortIndex\n  }))\n  |> drop(columns: [\"ifIndex\", \"ifIndex_str\"])  // Entfernen der alten Felder ifIndex und ifIndex_str\n  |> keep(columns: [\"_time\", \"PortIndex\", \"ifDescr\", \"ifName\"])  // Beibehalten der gewünschten Spalten\n\n// Retrieve LACP data\nlacp_data = from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  // Definieren des Zeitbereichs\n  |> filter(fn: (r) => r._measurement == \"LACP\")  // Filtern nach Messung \"LACP\"\n  |> filter(fn: (r) => r[\"source\"] == \"${Hostname}\")\n  |> filter(fn: (r) => r._field == \"lacpPortNumber\" or r._field == \"lacpPortState\" or r._field == \"lacpPortPartnerAdminState\" or r._field == \"lacpPortPartnerSystemID\" or r._field == \"lacpPortPartnerPortNumber\" or r._field == \"lacpPortPartnerKey\")  // Filtern nach relevanten Feldern\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Pivotieren der Daten, um Felder als Spalten zu haben\n  |> map(fn: (r) => ({ r with PortIndex: r.index }))  // Umbenennen des Index-Felds in PortIndex\n  |> keep(columns: [\"_time\", \"lacpPortNumber\", \"lacpPortState\", \"lacpPortPartnerAdminState\", \"lacpPortPartnerSystemID\", \"lacpPortPartnerPortNumber\", \"lacpPortPartnerKey\", \"PortIndex\"])  // Beibehalten der gewünschten Spalten\n\n// Join LACP data with interface descriptions\nlacp_with_interfaces = join(\n  tables: {interfaces: interfaces, lacp_data: lacp_data},  // Verbinden der beiden Datenströme\n  on: [\"_time\", \"PortIndex\"]  // Verbinden auf Basis der Zeit und PortIndex\n)\n\n// Ausgabe der kombinierten Daten\nlacp_with_interfaces\n  |> last(column: \"_time\")"
    }
   ]
  },
  {
   "title": "Interface In",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Statistics ifInDiscards",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IF\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifInDiscards\")\n  |> filter(fn: (r) => r[\"ifName\"] =~ /^${Interface:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"ifName\", \"_value\", \"_time\"])\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Interface Statistics ifInErrors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IF\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifInErrors\")\n  |> filter(fn: (r) => r[\"ifName\"] =~ /^${Interface:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"ifName\", \"_value\", \"_time\"])\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Interface Statistics ifInUnknownProtos",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IF\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifInUnknownProtos\")\n  |> filter(fn: (r) => r[\"ifName\"] =~ /^${Interface:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"ifName\", \"_value\", \"_time\"])\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Out",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Statistics ifHCOutOctets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IF\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifHCOutOctets\")\n  |> filter(fn: (r) => r[\"ifName\"] =~ /^${Interface:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"ifName\", \"_value\", \"_time\"])\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Interface Statistics ifOutDiscards",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IF\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifOutDiscards\")\n  |> filter(fn: (r) => r[\"ifName\"] =~ /^${Interface:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"ifName\", \"_value\", \"_time\"])\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Interface Statistics ifOutErrors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"cisconx9000\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"IF\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifOutErrors\")\n  |> filter(fn: (r) => r[\"ifName\"] =~ /^${Interface:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"ifName\", \"_value\", \"_time\"])\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}