{
 "title": "Linux Server Overview",
 "description": "Linux Server Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values(node_systemd_unit_state{instance=~\"$Hostname\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ping",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {instance=~\"$Hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$Hostname\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$Hostname\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$Hostname\"} * 100) / node_memory_MemTotal_bytes{instance=\"$Hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Space Used",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_free_bytes{instance=\"$Hostname\", mountpoint!=\"/boot/efi\", fstype!~\"(tmpfs|rootfs)\"}) / (node_filesystem_size_bytes{instance=\"$Hostname\", mountpoint!=\"/boot/efi\", fstype!~\"(tmpfs|rootfs)\"})) * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Service",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=\"$Hostname\", name=\"$Service\", state=~\"activating|active|deactivating|failed|inactive\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=\"$Hostname\"})by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=\"$Hostname\",mode='system'}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$Hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Space Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$Hostname\",fstype!~\"(tmpfs|rootfs)\", mountpoint!=\"/boot/efi\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=\"$Hostname\", name=\"$Service\", state=~\"activating|active|deactivating|failed|inactive\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{instance=~\"$Hostname\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$Hostname\"} > 0",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Hostname\"} > 0",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$Hostname\"} > 0",
     "legendFormat": "Available"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Disk Free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$Hostname\",fstype!~\"(tmpfs|rootfs)\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 41 },
   "options": {
    "content": "<div style=\"text-align: right;\">\n    <a href=\"https://furycode.org/\">\n        <img src=\"https://furycode.org/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fflame.26b9b203.png&w=640&q=75\" height=\"80\" alt=\"Flame\">\n    </a>\n</div>\n"
   }
  }
 ]
}