{
 "title": "PaloAlto PanOS Firewall",
 "description": "Dashboard for PaloAlto Firewalls",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "label": "Hostname",
    "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> keep(columns: [\"Hostname\"])\r\n  |> distinct(column: \"Hostname\")\r\n  |> group()"
   },
   {
    "name": "ActiveInterfaces",
    "label": "ActiveInterfaces",
    "query": "import \"strings\"\r\n\r\nfrom(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^IfOperStatus\\./)\r\n  |> filter(fn: (r) => r[\"_value\"] == 1)\r\n  |> map(fn: (r) => ({\r\n       _field: strings.split(v: r._field, t: \".\")[1], // Hier wird der Teil nach dem \".\" extrahiert\r\n       // Weitere Felder beibehalten\r\n       _measurement: r._measurement,\r\n       _time: r._time,\r\n       _value: r._value,\r\n     }))\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._field }))\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "day" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UpTime\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PanSystem\")\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 8640000.0 }))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PanSysSwVersion\")\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))\r\n"
    }
   ]
  },
  {
   "title": "Typ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PanTyp\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))"
    }
   ]
  },
  {
   "title": "HA State",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PanSysHaState\")\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._value }))\r\n"
    }
   ]
  },
  {
   "title": "Active Interface",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^IfDescr\\.${ActiveInterfaces:regex}$/)\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value}))"
    }
   ]
  },
  {
   "title": "Active Interface",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^IfOperStatus\\./)\r\n  |> filter(fn: (r) => r[\"_value\"] == 1)\r\n  |> map(fn: (r) => ({\r\n       _field: strings.split(v: r._field, t: \".\")[1], // Hier wird der Teil nach dem \".\" extrahiert\r\n       // Weitere Felder beibehalten\r\n       _measurement: r._measurement,\r\n       _time: r._time,\r\n       _value: r._value,\r\n     }))\r\n  |> last()\r\n  |> map(fn: (r) => ({ value: r._field }))\r\n"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Mgmt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pan_system",
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PanSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /HrProcessorLoad\\.\\d+/)\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")",
     "select": [
      [
       { "params": [ "hrProcessorLoad.1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Live Cluster CPU Load",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_hostname DP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pan_system",
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PanSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /HrProcessorLoad\\.\\d+/)\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")",
     "select": [
      [
       { "params": [ "hrProcessorLoad.2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan RPM Counters",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "pan_system",
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PanSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /Fan\\d+/)\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "fan1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Session & Packet Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Session",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PanSystem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PanSessionActiveTcp\" or r[\"_field\"] == \"PanSessionActiveUdp\" or r[\"_field\"] == \"PanSessionActiveICMP\") \r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Traffic in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^IfHcInOctets\\.${ActiveInterfaces:regex}$/)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 8 }))  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1m, nonNegative: false, columns: [\"_value\"])\r\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "Traffic out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"panos\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"Hostname\"] == \"${Hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^IfHcOutOctets\\.${ActiveInterfaces:regex}$/)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 8 }))  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1m, nonNegative: false, columns: [\"_value\"])\r\n  |> yield(name: \"derivative\")"
    }
   ]
  }
 ]
}